<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1e8249ff-6468-42ca-8197-7388b06e991a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Struct.App.Api.Client" Version="4.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delivery.Application\Delivery.Application.csproj" />
    <ProjectReference Include="..\Delivery.Composition\Delivery.Composition.csproj" />
  </ItemGroup>

</Project>
